### ISSUE TITLE
[Settings Cycler] Feature idea: cycle workspace / folder settings

### ISSUE THREAD

**Issue by forivall** [hoovercj/vscode-api-playground#15]
My use case is wanting to cycle the settings specifically in a single folder, specifically the hidden files setting, like
```json
{
  "files.exclude": {
    "src/**/*.d.ts": true,
    "src/**/*.js": true
  }
}
```
toggling that `true` vs `false`, to show/hide the files built alongside source `.ts` files.

**Comment by forivall** [comment]
Nevermind, there's extensions devoted to this use case. Thanks for this extension tho! I use it to toggle the opacity of lint warnings / errors.

**Comment by Chikowitz** [comment]
> Nevermind, there's extensions devoted to this use case. Thanks for this extension tho! I use it to toggle the opacity of lint warnings / errors.

@forivall hey, can you send the extensions you mentioned? Seems like I can't find them. I need to cycle settings on a folder level.
